// @file isr.zig
//
//  Interrupt handler config for STM32H563xx.
//  SPDX-License-Identifier: WTFPL
//

const main = @import("main.zig");

const Handler = *const fn () callconv(.c) void;

extern var _stack_top: usize;
export var vector_table linksection(".isr_vector") = [_]Handler {
    @ptrCast(&_stack_top), 		//  _estack
    main.start,	 				// Reset_Handler
    defaultHandler, 			// NMI_Handler
    defaultHandler, 			// HardFault_Handler
    defaultHandler, 			// MemManage_Handler
    defaultHandler, 			// BusFault_Handler
    defaultHandler, 			// UsageFault_Handler
    defaultHandler, 			// SecureFault_Handler
    defaultHandler, 			// reserved
    defaultHandler, 			// reserved
    defaultHandler, 			// reserved
    defaultHandler, 			// SVC_Handler
    defaultHandler, 			// DebugMon_Handler
    defaultHandler, 			// reserved
    defaultHandler, 			// PendSV_Handler
    defaultHandler, 			// SysTick_Handler
    defaultHandler, 			// WWDG_IRQHandler
    defaultHandler, 			// PVD_AVD_IRQHandler
    defaultHandler, 			// RTC_IRQHandler
    defaultHandler, 			// RTC_S_IRQHandler
    defaultHandler, 			// TAMP_IRQHandler
    defaultHandler, 			// RAMCFG_IRQHandler
    defaultHandler, 			// FLASH_IRQHandler
    defaultHandler, 			// FLASH_S_IRQHandler
    defaultHandler, 			// GTZC_IRQHandler
    defaultHandler, 			// RCC_IRQHandler
    defaultHandler, 			// RCC_S_IRQHandler
    defaultHandler, 			// EXTI0_IRQHandler
    defaultHandler, 			// EXTI1_IRQHandler
    defaultHandler, 			// EXTI2_IRQHandler
    defaultHandler, 			// EXTI3_IRQHandler
    defaultHandler, 			// EXTI4_IRQHandler
    defaultHandler, 			// EXTI5_IRQHandler
    defaultHandler, 			// EXTI6_IRQHandler
    defaultHandler, 			// EXTI7_IRQHandler
    defaultHandler, 			// EXTI8_IRQHandler
    defaultHandler, 			// EXTI9_IRQHandler
    defaultHandler, 			// EXTI10_IRQHandler
    defaultHandler, 			// EXTI11_IRQHandler
    defaultHandler, 			// EXTI12_IRQHandler
    defaultHandler, 			// EXTI13_IRQHandler
    defaultHandler, 			// EXTI14_IRQHandler
    defaultHandler, 			// EXTI15_IRQHandler
    defaultHandler, 			// GPDMA1_Channel0_IRQHandler
    defaultHandler, 			// GPDMA1_Channel1_IRQHandler
    defaultHandler, 			// GPDMA1_Channel2_IRQHandler
    defaultHandler, 			// GPDMA1_Channel3_IRQHandler
    defaultHandler, 			// GPDMA1_Channel4_IRQHandler
    defaultHandler, 			// GPDMA1_Channel5_IRQHandler
    defaultHandler, 			// GPDMA1_Channel6_IRQHandler
    defaultHandler, 			// GPDMA1_Channel7_IRQHandler
    defaultHandler, 			// IWDG_IRQHandler
    defaultHandler, 			// reserved
    defaultHandler, 			// ADC1_IRQHandler
    defaultHandler, 			// DAC1_IRQHandler
    defaultHandler, 			// FDCAN1_IT0_IRQHandler
    defaultHandler, 			// FDCAN1_IT1_IRQHandler
    defaultHandler, 			// TIM1_BRK_IRQHandler
    defaultHandler, 			// TIM1_UP_IRQHandler
    defaultHandler, 			// TIM1_TRG_COM_IRQHandler
    defaultHandler, 			// TIM1_CC_IRQHandler
    defaultHandler, 			// TIM2_IRQHandler
    defaultHandler, 			// TIM3_IRQHandler
    defaultHandler, 			// TIM4_IRQHandler
    defaultHandler, 			// TIM5_IRQHandler
    defaultHandler, 			// TIM6_IRQHandler
    defaultHandler, 			// TIM7_IRQHandler
    defaultHandler, 			// I2C1_EV_IRQHandler
    defaultHandler, 			// I2C1_ER_IRQHandler
    defaultHandler, 			// I2C2_EV_IRQHandler
    defaultHandler, 			// I2C2_ER_IRQHandler
    defaultHandler, 			// SPI1_IRQHandler
    defaultHandler, 			// SPI2_IRQHandler
    defaultHandler, 			// SPI3_IRQHandler
    defaultHandler, 			// USART1_IRQHandler
    defaultHandler, 			// USART2_IRQHandler
    defaultHandler, 			// USART3_IRQHandler
    defaultHandler, 			// UART4_IRQHandler
    defaultHandler, 			// UART5_IRQHandler
    defaultHandler, 			// LPUART1_IRQHandler
    defaultHandler, 			// LPTIM1_IRQHandler
    defaultHandler, 			// TIM8_BRK_IRQHandler
    defaultHandler, 			// TIM8_UP_IRQHandler
    defaultHandler, 			// TIM8_TRG_COM_IRQHandler
    defaultHandler, 			// TIM8_CC_IRQHandler
    defaultHandler, 			// ADC2_IRQHandler
    defaultHandler, 			// LPTIM2_IRQHandler
    defaultHandler, 			// TIM15_IRQHandler
    defaultHandler, 			// TIM16_IRQHandler
    defaultHandler, 			// TIM17_IRQHandler
    defaultHandler, 			// USB_DRD_FS_IRQHandler
    defaultHandler, 			// CRS_IRQHandler
    defaultHandler, 			// UCPD1_IRQHandler
    defaultHandler, 			// FMC_IRQHandler
    defaultHandler, 			// OCTOSPI1_IRQHandler
    defaultHandler, 			// SDMMC1_IRQHandler
    defaultHandler, 			// I2C3_EV_IRQHandler
    defaultHandler, 			// I2C3_ER_IRQHandler
    defaultHandler, 			// SPI4_IRQHandler
    defaultHandler, 			// SPI5_IRQHandler
    defaultHandler, 			// SPI6_IRQHandler
    defaultHandler, 			// USART6_IRQHandler
    defaultHandler, 			// USART10_IRQHandler
    defaultHandler, 			// USART11_IRQHandler
    defaultHandler, 			// SAI1_IRQHandler
    defaultHandler, 			// SAI2_IRQHandler
    defaultHandler, 			// GPDMA2_Channel0_IRQHandler
    defaultHandler, 			// GPDMA2_Channel1_IRQHandler
    defaultHandler, 			// GPDMA2_Channel2_IRQHandler
    defaultHandler, 			// GPDMA2_Channel3_IRQHandler
    defaultHandler, 			// GPDMA2_Channel4_IRQHandler
    defaultHandler, 			// GPDMA2_Channel5_IRQHandler
    defaultHandler, 			// GPDMA2_Channel6_IRQHandler
    defaultHandler, 			// GPDMA2_Channel7_IRQHandler
    defaultHandler, 			// UART7_IRQHandler
    defaultHandler, 			// UART8_IRQHandler
    defaultHandler, 			// UART9_IRQHandler
    defaultHandler, 			// UART12_IRQHandler
    defaultHandler, 			// SDMMC2_IRQHandler
    defaultHandler, 			// FPU_IRQHandler
    defaultHandler, 			// ICACHE_IRQHandler
    defaultHandler, 			// DCACHE1_IRQHandler
    defaultHandler, 			// ETH_IRQHandler
    defaultHandler, 			// ETH_WKUP_IRQHandler
    defaultHandler, 			// DCMI_PSSI_IRQHandler
    defaultHandler, 			// FDCAN2_IT0_IRQHandler
    defaultHandler, 			// FDCAN2_IT1_IRQHandler
    defaultHandler, 			// CORDIC_IRQHandler
     defaultHandler, 			// FMAC_IRQHandler
    defaultHandler, 			// DTS_IRQHandler
    defaultHandler, 			// RNG_IRQHandler
    defaultHandler, 			// reserved
    defaultHandler, 			// reserved
    defaultHandler, 			// HASH_IRQHandler
    defaultHandler, 			// reserved
    defaultHandler, 			// CEC_IRQHandler
    defaultHandler, 			// TIM12_IRQHandler
    defaultHandler, 			// TIM13_IRQHandler
    defaultHandler, 			// TIM14_IRQHandler
    defaultHandler, 			// I3C1_EV_IRQHandler
    defaultHandler, 			// I3C1_ER_IRQHandler
    defaultHandler, 			// I2C4_EV_IRQHandler
    defaultHandler, 			// I2C4_ER_IRQHandler
    defaultHandler, 			// LPTIM3_IRQHandler
    defaultHandler, 			// LPTIM4_IRQHandler
    defaultHandler, 			// LPTIM5_IRQHandler
    defaultHandler 				// LPTIM6_IRQHandler
};

fn defaultHandler() callconv(.c) void {
    // TODO: read ID, disable interrupt, then dead loop.
    while (true) {}
}
